### ISSUE TITLE
onHomeIconPressed when app was terminated

### ISSUE THREAD

**Issue by hannes-k** [EddyVerbruggen/cordova-plugin-3dtouch#1]
Hi,

1. Thank you for your great work and plugin!

2. I've got a problem, if the app is terminated. When I'm starting the app by a force touch shortcut, the onHomeIconPressed function doesn't get called. When the app was launched before and is cached, everything works as expected.

Is this a known problem? 

Best
Hannes

**Comment by abalonebao** [comment]
I've solved this issue~
In XCode, you need to update "plugin/AppDelegate+threedeetouch.m"

Update this line:
------
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 25 * NSEC_PER_MSEC), dispatch_get_main_queue(), ^{

With this line:
------
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 450 * NSEC_PER_MSEC), dispatch_get_main_queue(), ^{

just like this
<img width="932" alt="screen shot 2015-10-15 at 3 33 23 am" src="https://cloud.githubusercontent.com/assets/8255349/10495254/8c701308-72ed-11e5-9132-b9dc5d4b3d6b.png">

I slow down the dispatch delay time and it works~

lol this is my first comment in github, hope my answer can help you~

**Comment by EddyVerbruggen** [comment]
Hey @hannes-k thanks for sharing your observation! I will take a look and see if it can be further optimized (stretching the timeout may result in your app briefly showing a page before responding to the shortcut action).

**Comment by EddyVerbruggen** [comment]
I'm not sure how precise that 450ms is - could you please test v1.0.1 of this plugin and see if it's ok as well?

Btw, which device are you on? 6S or 6S Plus?

**Comment by abalonebao** [comment]
I was keep testing with different value of ms and 450 is pretty good...
me iphone is 6s plus

**Comment by abalonebao** [comment]
will test 1.0.1 later~it's 4am in hk...

**Comment by EddyVerbruggen** [comment]
Wahaha, go (back) to sleep :+1:

**Comment by abalonebao** [comment]
sosad... not working#1.0.1

**Comment by abalonebao** [comment]
oh wait....it works (sometimes)

**Comment by EddyVerbruggen** [comment]
@abalonebao Please tty 1.1.0 that should def fix the issue.

**Comment by abalonebao** [comment]
it's weird... not working #1.1.0

**Comment by EddyVerbruggen** [comment]
Can you share you project with me perhaps?

**Comment by hannes-k** [comment]
Hey @EddyVerbruggen 

I updated to 1.1.0 and on my iPhone 6s the bug seems to be fixed. Now everything works as expected! Thank you very much!

**Comment by EddyVerbruggen** [comment]
:+1:

**Comment by Hirbod** [comment]
I can confirm. Works as expected
