### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by array-addu** [EddyVerbruggen/cordova-plugin-3dtouch#11]
I'm testing this plugin on iPhone 6s (iOS ver.-9.2) and app was build with Xcode 7 as per the minimum requirements of this plugin to work, but when i'm checking the availability of the plugin, the following code returns me false, am i dong something wrong?

ThreeDeeTouch.isAvailable(function (avail) {
    // 'avail' is a boolean
    alert("avail? " + avail)
  });

**Comment by EddyVerbruggen** [comment]
- Are you waiting for `deviceready` to fire before running that code?
- Are you running this on a real device?

**Comment by array-addu** [comment]
yes, actually i'm implementing this in meteor, in meteor, `Meteor.startup()` is equivalent to `device ready`.
and yes i've checked it on iPhone 6, iPhone +,iPhone 6s but it's giving `false` on each of them.

**Comment by EddyVerbruggen** [comment]
I don't use meteor but there are folks using meteor using this plugin so it should be possible. Can you consult the meteor forum?

**Comment by array-addu** [comment]
I have put this on Meteor forum but there is no response yet. Can you suggest me the possible reasons why it's giving me false if i met all minimum requirements for this plugin to work?

**Comment by EddyVerbruggen** [comment]
If you can debug your code in Xcode add a breakpoint [here](https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/blob/master/src/ios/app/ThreeDeeTouch.m#L16) - otherwise use Google/StackOverflow as I know nothing about Meteor. Or ask the guys I responded to in #4 (also Meteor users).

**Comment by array-addu** [comment]
Thank you for giving reference.
