### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by theHellyar** [EddyVerbruggen/cordova-plugin-3dtouch#13]
getting this error when I build:

` The following build commands failed:
	CompileC build/onBudget.build/Debug-iphonesimulator/onBudget.build/Objects-normal/i386/AppDelegate+threedeetouch.o onBudget/Plugins/cordova-plugin-3dtouch/AppDelegate+threedeetouch.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/onBudget.build/Debug-iphonesimulator/onBudget.build/Objects-normal/i386/ThreeDeeTouch.o onBudget/Plugins/cordova-plugin-3dtouch/ThreeDeeTouch.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)`

might help to note I followed this walk thru: http://gonehybrid.com/how-to-set-up-quick-actions-with-3d-touch-for-your-ionic-app/
- but used bleeding edge repo, as the other was giving 404 error

**Comment by theHellyar** [comment]
*Dang I feel like a noob. please mark as solved. Needed to remove the iOS platform and re-add it again to propagate the threeDeeTouch plugin

**Comment by EddyVerbruggen** [comment]
No worries, thanks for the follow-up.
