### ISSUE TITLE
hi need help with   ThreeDeeTouch.enableLinkPreview();

### ISSUE THREAD

**Issue by ezazwar1** [EddyVerbruggen/cordova-plugin-3dtouch#15]
Hi @EddyVerbruggen  i am keen to learn how the peek and pop works there is some detail in the Documentation but i cant figure out how to make a peek and pop work

Correct me if i am wrong
when you enable enableLinkPreview does that call
 ```
 ThreeDeeTouch.watchForceTouches(function(result) {
    console.log("force touch % " + result.force); // 84
    console.log("force touch timestamp " + result.timestamp); // 1449908744.706419
    console.log("force touch x coordinate " + result.x); // 213
    console.log("force touch y coordinate " + result.y); // 41
  });
```
or Does it automatically Popup but what is shown in popup

Its Really confusing me
Please Help as i have gone through the https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/ where does this plugin fit in 

how can one configure the peek and the peek options

Regards
Ezaz

**Comment by EddyVerbruggen** [comment]
Peek and Pop is only supported for links, just like in a browser on a mobile device supporting 3D Touch. The only thing this plugin can do is enabling that "press hard on a link to peek and pop" feature. `watchForceTouches` has nothing to do with that.

**Comment by ezazwar1** [comment]
Ok thanks for clearing the doubts
