### ISSUE TITLE
When adding custom list of actions, default Share App disappears.

### ISSUE THREAD

**Issue by waparty** [EddyVerbruggen/cordova-plugin-3dtouch#18]
When adding custom list (i.e. static list via .plist file) of actions, default 'Share App' button disappears.

**Comment by EddyVerbruggen** [comment]
What do the Apple docs say about this behaviour?

**Comment by waparty** [comment]
As I checked, there is no any examples for that share button, but I see some apps has it with together with other items.
In my case, if there is no any custom items on force touch, then Share App appears as a default, but when I add my items to .plist, then Share App is not available. Any ideas?

**Comment by waparty** [comment]
`      <dict>
        <key>UIApplicationShortcutItemIconType</key>
        <string>UIApplicationShortcutIconTypeShare</string>
        <key>UIApplicationShortcutItemTitle</key>
        <string>Share the app</string>
        <key>UIApplicationShortcutItemType</key>
        <string>$(PRODUCT_BUNDLE_IDENTIFIER).Share</string>
      </dict>`

I tried this, but it just opens app, not sharing...

**Comment by EddyVerbruggen** [comment]
That's all very clear, but the question remains: what's Apple's spec regarding this? It's not that this plugin tries to actively add or remove that default button.

**Comment by waparty** [comment]
http://stackoverflow.com/questions/39440756/share-app-application-shortcut-uiapplicationshortcuticontypeshare/39749606#39749606

Seems like this might be a case...

**Comment by EddyVerbruggen** [comment]
Ah, so that makes sense - it's not the for local builds but will be added when downloaded from the AppStore (since iOS 10), right?

**Comment by waparty** [comment]
Seems like yes... :) Interesting why there are only a few people that facing this issue...
