### ISSUE TITLE
Phonegap Build - No Quick Actions

### ISSUE THREAD

**Issue by xmetalmw** [EddyVerbruggen/cordova-plugin-3dtouch#19]
Hi! I would absolutely LOVE to get this plugin working, but so far I've not been able to get anything to happen. Here's the details:

- Using Phonegap build with their latest build version (6.3.0)
- Gap plugin tag: <gap:plugin name="cordova-plugin-3dtouch" source="npm" />
- App builds successfully with no issues and works perfectly otherwise
- Tested on iPhone 7+ with iOS 10.0.2

In my index.html I have a deviceready listener:

` document.addEventListener('deviceready', start3Dtouch(), false);`

start3Dtouch() is in my primary js file, which is already loaded. The function is firing, I get the alert on app load. The js below is probably the 30th permutation, I've tried many combos and this is about as simplified as I can make it. 

```
function start3Dtouch() {
	
	alert("start3dtouch");
	
	ThreeDeeTouch.configureQuickActions([
      {
        type: 'scan', // optional, but can be used in the onHomeIconPressed callback
        title: 'Attendance', // mandatory
        subtitle: 'Scan QR Code to checkin at event', // optional
        iconType: 'MarkLocation' // optional
      },
      {
        type: 'evals',
        title: 'Evaluations',
        iconType: 'Task' // optional, case insensitive
      },
      {
        type: 'transcript',
        title: 'Transcript',
        iconType: 'Message' // iconType is case insensitive
      },
      {
        type: 'calendar',
        title: 'Calendar',
        iconType: 'Invitation' // iconType is case insensitive
      }
    ]);
    
    ThreeDeeTouch.onHomeIconPressed = function(payload) {
        alert(payload.type);
	}
}
```

If I launch the app, I see the alert. If I go back to the home screen on my phone and force touch the icon, I get the haptic feedback and the screen blurs for a moment but I've never gotten the menu of my options. Any suggestions would be greatly appreciated and thank you very much for your work to create these plugins!

**Comment by EddyVerbruggen** [comment]
Hi,

You're seeing the alert on app launch because you're immediately invoking `start3Dtouch()` (not waiting for `deviceready`. Just drop a global JS catch-all error handler and you'll prolly see an error at the line `ThreeDeeTouch.configureQuickActions`.

Add this to the head of your index.html:
```js
window.onerror = function (a,b,c) {
  alert(a + ", " + b + ", " +c);
}
```

Rewrite the listener to `document.addEventListener('deviceready', start3Dtouch, false);`should yield better results.

**Comment by xmetalmw** [comment]
OMGoodness, it looks like the stinking () was the culprit. I've had those in other eventListeners for a long time with no apparent issue. Thanks very much for the tip, the quick access menu is popping up nicely now!
