### ISSUE TITLE
ThreeDeeTouch.onHomeIconPressed not working

### ISSUE THREAD

**Issue by vespino** [EddyVerbruggen/cordova-plugin-3dtouch#21]
Trying to enhance one of my apps using this plugin. ThreeDeeTouch.configureQuickActions works great and I'm able to open the app using a QuickAction, but this action doesn't seem to be detected in the app. Only thing I have for now to see if the function works is the following:

    		ThreeDeeTouch.onHomeIconPressed = function(payload) {alert(payload.type);
				if(payload.type=='play_last') {

				}else{
					console.log(JSON.stringify(payload));
				}
			}

This is in a function called onDeviceReady I run on "deviceready":

document.addEventListener("deviceready", onDeviceReady, false);

Any ideas on this?

**Comment by EddyVerbruggen** [comment]
Can you share the entire file this is in? Either the html or js file..

**Comment by vespino** [comment]
I have attached the file.

[jquery.zip](https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/files/536171/jquery.zip)

**Comment by vespino** [comment]
Can you help me with my project?

**Comment by EddyVerbruggen** [comment]
Looks ok. Dunno what the problem is. Can you try creating a plain new Cordova app and try to get it working?

**Comment by vespino** [comment]
Found the issue, apparently a conflict with another plugin :(

Needle in a haystack!
