### ISSUE TITLE
iconTemplate

### ISSUE THREAD

**Issue by videmort** [EddyVerbruggen/cordova-plugin-3dtouch#22]
How I can add the icon inside the Asset catalog?
I want to use one custom icon but i don't know how. 
Thanks

**Comment by EddyVerbruggen** [comment]
What have you tried already?

**Comment by videmort** [comment]
Nothing because I don't know who to do that :(

**Comment by videmort** [comment]
I'm using ionic/cordova

**Comment by videmort** [comment]
@EddyVerbruggen  I tried to copy the icon inside the  resources/ios folder in cordova/ionic app

**Comment by videmort** [comment]
Hi again, Working fine. The problem is that cordova doesn't copy icons to asset catalog automatically.

**Comment by vespino** [comment]
Could you explain this some more? How should my file/directory structure look like afterwards?

**Comment by videmort** [comment]
Hi, I can explain vía teamViewer if you want :)

**Comment by vespino** [comment]
I would like to know how to add an option with my own custom icon. I know by now that I have to use the iconTemplate but then what?

**Comment by videmort** [comment]
You need to add manually the icon that you want to use in xCode asset
catalog

**Comment by vespino** [comment]
And what if I don't use Xcode or even a Mac for that matter?

**Comment by videmort** [comment]
You need to create the assets in xCode that assets generated one folder
with the img and json data.
You can copy that folder and create one before compile hook in cordova.
In that hook you can copy and paste the assets :)

**Comment by vespino** [comment]
Like I said, no Xcode :( I will have to find some other solution then.

**Comment by videmort** [comment]
If you send to me the images I can generate to you the assets :)

**Comment by vespino** [comment]
I that would be great. I will do that this week.

**Comment by videmort** [comment]
Perfect :)

**Comment by vespino** [comment]
Can you tell me what you need exactly? Do the images require certain specs?

**Comment by videmort** [comment]
Png :)

**Comment by vespino** [comment]
Ok, but what about pixels?

**Comment by videmort** [comment]
https://developer.apple.com/ios/human-interface-guidelines/resources/
Here you have got one psd

**Comment by vespino** [comment]
I have downloaded 3 icons, can you work with this?

[icons.zip](https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/files/606536/icons.zip)

**Comment by videmort** [comment]
Take. Copy this folder into --> Platforms-->ios--> (Proyect Name ) --> Images.xcassets 

And it's all you will have the custom icon.
Remember that if you do one ionic state reset or you destroy the platform the icons is going to be deleted too!!

You should create one hook before compile to copy the icons in that folder.

Icons name for iconTemplate -->cart, detail, list

[icons.zip](https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/files/606675/icons.zip)

**Comment by vespino** [comment]
Thanks. I'm using Phonegap Build which uses a different directory structure (I think):

Payload
- projectname.app
- - _CodeSignature
-- CDVNotification.bundle
-- www

Do I have to change this IPA file which PGB provides before sending it to Apple? I guess not?

**Comment by videmort** [comment]
Mmmmm can we have one team viewer sesion?
I can't help you if I don't see your estructure

**Comment by vespino** [comment]
We can. What is your mail address, I will send you the teamviewer data.

**Comment by videmort** [comment]
f.carrasco.marcos24@gmail.com

**Comment by vespino** [comment]
You've got mail :)

**Comment by vespino** [comment]
@EddyVerbruggen I had a Skype call with @videmort last night and we agreed on the following feature request: if you have the time, would it be possible to use icons located inside the project directory? I'm using Phonegap Build and there is no way for me to use the iconTemplate since I don't have access to the assets folder in the project structure since PGB works very differently. If it would be possible to place the images inside my project directory (next to my other images) and use a parameter iconLocation (or whatever) and set this to "images/icon.png" that would be great!

Please consider this request.

**Comment by EddyVerbruggen** [comment]
Hi @vespino [this is Apple's spec](https://developer.apple.com/reference/uikit/uiapplicationshortcuticon/1623367-iconwithtemplateimagename?language=objc), so I'm not sure that would be possible.

**Comment by vespino** [comment]
@EddyVerbruggen I have faith in your programming skills :)
