### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by vespino** [EddyVerbruggen/cordova-plugin-3dtouch#23]
Is it possible to add custom icons? And is it possible to position the icons on the right?

**Comment by EddyVerbruggen** [comment]
- Yes, as indicated in the readme
- That's up to iOS; when your app icon is on the right side of the screen the quicklaunch icons are on the right as well (see the screenshots in the readme)

**Comment by vespino** [comment]
iconTemplate, correct? Could you give or add an example of how this must be used using my own icon?
