### ISSUE TITLE
Opening IOS native share window

### ISSUE THREAD

**Issue by giftstart** [EddyVerbruggen/cordova-plugin-3dtouch#26]
Hi,

I was wondering how can I open the native IOS share window without launching the app itself? Most of the apps have a 'share' quick action option when pressing the app icon and when the 'share' option is chosen the app doesn't launch, it just opens the IOS native share window. Is this possible? Every thing I code in onHomeIconPressed function is triggered after the app is launched which is what I don't want.

Thanks for your help,
Sean

**Comment by EddyVerbruggen** [comment]
It's something iOS does automatically. Please Google how it does that and report back.

**Comment by skotturi** [comment]
@giftstart were you able to find a solution to this? 

I'm trying to implement "Share App" that all apps seem the option when you 3DTouch the icon. 

ionic has a `ionic.Platform.exitApp()` but this depends on https://www.npmjs.com/package/cordova-plugin-exitapp which states it only works on Android and Windows phone. 

I'm left without a way of keeping the user out of the app, oh well, I just make sure they end up on the home view of my app.

**Comment by giftstart** [comment]
As Eddy mentioned it is something automatic, you don't need to code it but it only works on a 'production' build, it won't work on development builds.

**Comment by EddyVerbruggen** [comment]
Thanks, @giftstart!

**Comment by skotturi** [comment]
Just to clarify, the "it is something automatic" is: iOS will add the Share option automatically to apps that are installed through the App Store (in production) and so this is something we should NOT implement ourselves. 

When I read "it is automatic", I thought we meant that this plugin automatically handles the share intent on launch and thus there was nothing we could/needed to do to prevent the app from launching.
