### ISSUE TITLE
Static quick actions

### ISSUE THREAD

**Issue by iampeter** [EddyVerbruggen/cordova-plugin-3dtouch#3]
Would be great if it was possible to add predefined static quick actions in the plugin config, so that we can have quick actions available right after the app installation. For example:

- Shortcut 1 -> index.html#functionality-1
- Shortcut 2 -> index.html#functionality-2
- Shortcut 3 -> other.html

Also with custom icons if possible.

**Comment by EddyVerbruggen** [comment]
Hey @iampeter thanks for your feature request. It has now been implemented and documented in the readme.

Available in 1.2.1, tested with the CLI and Telerik Platform, including those cool custom icons.

Cheers,
Eddy
