### ISSUE TITLE
error installing  through repository

### ISSUE THREAD

**Issue by ang3lx** [EddyVerbruggen/cordova-plugin-3dtouch#5]
Hello, 
what's wrong?

iMac:IVGBlog Nello$ cordova plugin add cordova-plugin-3dtouch
Fetching plugin "cordova-plugin-3dtouch" via npm
Plugin "cordova-plugin-3dtouch" already installed on android.
Plugin "cordova-plugin-3dtouch" already installed on ios.
Error during processing of action! Attempting to revert...
Error: Uh oh!
Invalid Version: undefined

**Comment by EddyVerbruggen** [comment]
Seems like you already have it (at least, that's what your logs thinks). Could you do a `cordova plugins list` and see if that's the case, and remove it first?

Otherwise: can you try a vanilla CLI project and see if you can add it?

**Comment by ang3lx** [comment]
I've problem to add and remove it
when I add it, i've got an error, but with cordova plugins list I can see it.


![schermata 2015-11-30 alle 12 08 54](https://cloud.githubusercontent.com/assets/1527093/11470069/2db263d8-975b-11e5-9600-aaa5b421d52a.png)

**Comment by EddyVerbruggen** [comment]
That's more of a problem with the CLI I'd say. Can't really help you there. If the plugin doesn't correctly install in a new CLI project then please reopen this issue.
