### ISSUE TITLE
No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

### ISSUE THREAD

**Issue by Jarvey** [EddyVerbruggen/cordova-plugin-3dtouch#7]
Hi I  updated my cordova project to 4.0.0 (ionic platform update ios@4.0.0)

When I build the project in xcode I get the following error in de AppDelegate+threedeetouch.m file line 20: "No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'"

**Comment by EddyVerbruggen** [comment]
Thanks for reporting that! Fixed in version 1.3.2.

**Comment by ImranHParkResorts** [comment]
Hello Jarvey, 

  I've recently updated my cordova ios project and getting the same error. I can't really find the fix. Can you please help me here?

Thanks

**Comment by Jarvey** [comment]
@ImranHParkResorts: After posting my issue here EddyVerbruggen made a fix in the plugin and released a new version, so the only thing I had to was updating this plugin in my project to the newest version and than it was solved my case.
