### ISSUE TITLE
Cannot use UIApplicationShortcutItemIconFile in PGB

### ISSUE THREAD

**Issue by mgoetz85** [EddyVerbruggen/cordova-plugin-3dtouch#9]
Hi,

First of all - great plugin. Works great, also via PGB.

However, one thing which does not work (or I am not managing to get it working) is the definition of custom icons via UIApplicationShortcutItemIconFile.

I include the plugin via my config.xml:
`<plugin name="cordova-plugin-privacyscreen" spec="https://github.com/devgeeks/PrivacyScreenPlugin.git" source="git" />`

Furthermore I adjust the .plist (again via  config.xml):
`<gap:config-file platform="ios" parent="UIApplicationShortcutItems">
	<array>
		<dict>
			<key>UIApplicationShortcutItemIconType</key>
			<string>UIApplicationShortcutIconTypeCloud</string>
			<key>UIApplicationShortcutItemTitle</key>
			<string>Cloud</string>
			<key>UIApplicationShortcutItemSubtitle</key>
			<string>Awesome subtitle</string>
			<key>UIApplicationShortcutItemType</key>
			<string>eyefromplist</string>
		</dict>
		<dict>
			<key>UIApplicationShortcutItemIconType</key>
			<string>UIApplicationShortcutIconTypeCompose</string>
			<key>UIApplicationShortcutItemTitle</key>
			<string>Compose</string>
			<key>UIApplicationShortcutItemSubtitle</key>
			<string>Foo bar</string>
			<key>UIApplicationShortcutItemType</key>
			<string>compose</string>
		</dict>
		<dict>
			<key>UIApplicationShortcutItemIconFile</key>
			<string>VIP</string>
			<key>UIApplicationShortcutItemTitle</key>
			<string>Virtual Promoter</string>
			<key>UIApplicationShortcutItemSubtitle</key>
			<string>Pin a picture</string>
			<key>UIApplicationShortcutItemType</key>
			<string>pinpicture</string>
		</dict>
	</array>
</gap:config-file>`

The file VIP.png is stored in the root folder of the PGB zip - however the shortcut menu does not show the image (it shows the entry in general but not the image).

Any ideas?

Thanks in advance.

**Comment by EddyVerbruggen** [comment]
It doesn't work when in the www folder, it needs to be in the resources bundle which AFAIK is not possible on PhoneGap Build.
